### PR TITLE
Update code and api-common submodule to use v1 paths

### PR DESCRIPTION
**Pull request by Marenz**
Otherwise we can't use other code that uses v1. paths.

~Depends on https://github.com/frequenz-floss/frequenz-api-dispatch/pull/137~

### CODE REVIEW

**Review by stefan-brus-frequenz — DISMISSED** [review]

**Review by stefan-brus-frequenz — DISMISSED** [review]

**Comment by Marenz** [comment]
@llucax any idea what's with the cross-arch tests?

**Review by llucax — DISMISSED** [review]
You need to also bump the dependency in `pyproject.toml`. Have a look at: https://github.com/frequenz-floss/frequenz-api-dispatch/blob/v0.x.x/CONTRIBUTING.md#upgrading-dependencies

You also need to update the `mkdocs.yaml` file to make the cross-linking is pointing to the new version too, we should update the `CONTRIBUTING.md` file to reflect that:

**Comment by Marenz** [comment]
pyproject already has the latest, updated the docs

**Review by stefan-brus-frequenz — APPROVED** [review]

**Comment by llucax** [comment]
* https://github.com/frequenz-floss/frequenz-repo-config-python/pull/223

**Comment by llucax** [comment]
> pyproject already has the latest, updated the docs

Oh, OK, so that was bumped before without actually bumping the submodule?

**Pull request merged**
