### PR TITLE
Update frequenz-api-common to 0.5

### PR DESCRIPTION
**Pull request by Marenz**
So it's in sync with frequenz-api-microgrid.
Also updates further dependencies to avoid conflicts.

### CODE REVIEW

**Review by llucax — APPROVED** [review]
LGTM but I wonder if some of the stuff used in this API is not available in common now. Did you check for that?

Also, if there are no changes relevant to us between 0.3 and 0.5, you can just widen the dependency instead of bumping the minimum version to minimize breakage (but I guess in this case there is nothing else using 0.3 or 0.4)

**Comment by Marenz** [comment]
>  is not available in common now

which common now?

**Comment by stefan-brus-frequenz** [comment]
> which common now?

https://github.com/frequenz-floss/frequenz-api-common/

**Comment by stefan-brus-frequenz** [comment]
Ah yeah... There are a few "commons"

**Review by stefan-brus-frequenz — APPROVED** [review]

**Comment by Marenz** [comment]
> Also, if there are no changes relevant to us between 0.3 and 0.5,

I can't go lower because [0.5.4 updates the google min dependency](https://github.com/frequenz-floss/frequenz-api-common/commit/6cf10e861e3657c66fe2c4080242216a211a1762) and then the test_min fails because it can't find any candidate that satisfies all min deps.

**Pull request merged**
