### PR TITLE
Fix pagination response and add docu

### PR DESCRIPTION
**Pull request by Marenz**
The original PR added the wrong field `pagination_parameters` twice, it should have been `pagination_info` in the response message.

### CODE REVIEW

**Review by llucax — DISMISSED** [review]

**Comment by Marenz** [comment]
Added relelase notes

**Review by llucax — DISMISSED** [review]

**Review by llucax — APPROVED** [review]
GitHub support for changes in submodules it quite crappy, maybe you can mention why the update? I guess you have a valid reason so approving.

**Comment by Marenz** [comment]
We changed the structure of the pagination message in the common-api

**Comment by llucax** [comment]
Is the `oneof` thing?

**Pull request merged**
