### PR TITLE
Improve and fix documentation

### PR DESCRIPTION
**Pull request by llucax**
- Move the service documentation to the `service` block (workaround for #67)
- Use markdown formatting
- Use syntax highlight for examples in docs
- Add link to the RFC

### CODE REVIEW

**Comment by llucax** [comment]
image

image

**Comment by llucax** [comment]
Updated. I'm not sure what's the current status of this intro doc in other API, because I did this a long time ago and maybe things changed.

**Review by Marenz — APPROVED** [review]

**Comment by llucax** [comment]
@stefan-brus-frequenz maybe you want to approve this too as you are more up to date to how API repos should be?

**Comment by Marenz** [comment]
@stefan-brus-frequenz ping

**Review by stefan-brus-frequenz — APPROVED** [review]

**Pull request merged**
